#!/usr/bin/env node
// Scaffolds a new trip folder — see DEV_NOTES.md "To start a new real trip".
// This used to be five manual steps (copy the engine file, hand-edit
// TRIP_ID/TRIP_LABEL/TRIP_SEED, update <title>, write a manifest.json,
// remember to point the manifest icon/scope correctly) — easy to typo a
// tripId/folder-name mismatch. This script does all of it from one seed
// JSON file.
//
// It reads the LIVE engine file (repo-root index.html) as its template,
// rather than a separate hardcoded copy baked into this script, so a
// scaffolded trip always matches whatever the dashboard actually looks
// like today — if the HTML/CSS shell ever changes, this script doesn't
// need updating to match.
//
// Usage:
//   node scripts/new-trip.mjs <slug> <label> <seed.json>
//
//   <slug>      folder name AND Firebase tripId — lowercase, hyphenated,
//               e.g. summer-2027. These MUST match (see DEV_NOTES.md).
//   <label>     short label shown in the ticket stub, e.g. "SUMMER · 2027"
//   <seed.json> path to a JSON file shaped like TRIP_SEED in DEV_NOTES.md —
//               see scripts/new-trip.example.json for a starter you can copy.
//
// Example:
//   node scripts/new-trip.mjs summer-2027 "SUMMER · 2027" scripts/new-trip.example.json

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

const [, , slug, label, seedPath] = process.argv;
if (!slug || !label || !seedPath) {
  console.error('Usage: node scripts/new-trip.mjs <slug> <label> <seed.json>');
  console.error('See the comment at the top of this file for the seed.json shape,');
  console.error('or copy scripts/new-trip.example.json as a starting point.');
  process.exit(1);
}
if (!/^[a-z0-9-]+$/.test(slug)) {
  console.error(`Slug "${slug}" should be lowercase letters/digits/hyphens only — it becomes both the folder name and the Firebase tripId, and DEV_NOTES.md requires those to match.`);
  process.exit(1);
}

const tripDir = path.join(repoRoot, slug);
if (fs.existsSync(tripDir)) {
  console.error(`${tripDir} already exists — refusing to overwrite an existing trip.`);
  process.exit(1);
}

let seed;
try {
  seed = JSON.parse(fs.readFileSync(seedPath, 'utf8'));
} catch (e) {
  console.error(`Couldn't read/parse seed file "${seedPath}": ${e.message}`);
  process.exit(1);
}
const title = seed.meta?.title || label;

const enginePath = path.join(repoRoot, 'index.html');
const engineHtml = fs.readFileSync(enginePath, 'utf8');

const escapedTitle = title.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
let html = engineHtml.replace(/<title>[^<]*<\/title>/, `<title>${escapedTitle}</title>`);

// The engine's module script block always looks like the "PER-TRIP SETTINGS"
// comment followed by an initTripDashboard({...}) call — see index.html
// itself. If someone reshapes that block, this deliberately fails loudly
// rather than silently scaffolding a broken trip file.
const scriptBlockRe = /<script type="module">[\s\S]*?<\/script>/;
if (!scriptBlockRe.test(html)) {
  console.error(`Could not find the <script type="module"> block in ${enginePath} — has the engine template changed shape? Update this script's scriptBlockRe if so.`);
  process.exit(1);
}
const seedJson = JSON.stringify(seed, null, 2).replace(/\n/g, '\n    ');
const newScript = `<script type="module">
  import { initTripDashboard } from '../app.js';

  // ============================================================
  // PER-TRIP SETTINGS — see DEV_NOTES.md "Extract shared engine
  // into app.js" — all rendering/sync logic lives there now.
  // Generated by scripts/new-trip.mjs — safe to hand-edit after.
  // ============================================================
  initTripDashboard({
    tripId: ${JSON.stringify(slug)},
    tripLabel: ${JSON.stringify(label)},
    tripSeed: ${seedJson},
  });
</script>`;
html = html.replace(scriptBlockRe, newScript);

fs.mkdirSync(tripDir);
fs.writeFileSync(path.join(tripDir, 'index.html'), html);

const manifest = {
  name: title,
  short_name: label.length <= 12 ? label : label.slice(0, 12),
  start_url: '.',
  scope: '.',
  display: 'standalone',
  background_color: '#F0EEE6',
  theme_color: '#16233F',
  icons: [{ src: '/trip-dashboard/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' }],
};
fs.writeFileSync(path.join(tripDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

console.log(`Created ${tripDir}${path.sep}`);
console.log(`  - index.html  (tripId: ${slug})`);
console.log('  - manifest.json');
console.log('');
console.log('Next steps (see DEV_NOTES.md "To start a new real trip"):');
console.log('  1. git add, commit, push from this clone.');
console.log('  2. GitHub Pages redeploys in ~1-2 min.');
console.log(`  3. Open https://qloof.github.io/trip-dashboard/${slug}/ once to trigger the seed-on-first-load, confirm "Synced".`);
